AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    streaming data consumer lambda
Resources:
    # KinesisStream:
    #   Type: AWS::Kinesis::Stream
    #   Properties:
      
    #     Name: telemetry-power-consumption 
    #     ShardCount: 1

    ConsumerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConsumerTable
        AttributeDefinitions:
          - AttributeName: Date
            AttributeType: S
          - AttributeName: Time
            AttributeType: S
                                    
        KeySchema:
          - AttributeName: Date
            KeyType: HASH
          - AttributeName: Time
            KeyType: RANGE                                                                        
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5    

    ConsumerLambda:
        Type: AWS::Serverless::Function
        Properties:
            Handler: main.lambda_handler
            Runtime: python3.7
            MemorySize: 256
            Timeout: 10
            Events:
              Stream:
                Type: Kinesis
                Properties:
                  Stream: !Getatt stream.arn #arn of the stream
                  StartingPosition: LATEST
                  BatchSize: 1
            Policies:
              - AmazonDynamoDBFullAccess
            Role: !Sub #arn of AWSLambdaKinesisExecutionRole

