AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    predict and store in dynamodb
Resources:
    RoutePredictionsLambda:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiEvent:
                    Properties:
                        RestApiId:
                            Ref: RoutePredictionsGateway
                        Path: /{proxy+}
                        Method: ANY
                    Type: Api
            FunctionName: route-predictions-userid
            CodeUri: ./
            Handler: main.handler
            Runtime: python3.7
            Timeout: 900 # timeout of your lambda function
            MemorySize: 2048 # memory size of your lambda function
            Description: predict and store in dynamodb
            # other options, see ->
            # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html#sam-specification-template-anatomy-globals-supported-resources-and-properties
            Role: !Sub #AWSLambdaBasicExecutionRole

    RoutePredictionsGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: prod
            OpenApiVersion: '3.0.0'
